name: cd flow

on:
    workflow_run:
        workflows: ["ci flow"]
        types: [completed]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.HOST }}
                username: ubuntu
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    set -e

                    if [ ! -d "ci-cd-with-github-action" ]; then
                    git clone https://github.com/solankiakash775-create/ci-cd-with-github-action.git
                    fi

                    cd ci-cd-with-github-action
                    git pull origin main

                    docker compose down
                    docker compose pull
                    docker compose up -d 

              


    