name: cd flow

on:
    workflow_run:
        workflows: ["ci flow"]
        types: [completed]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                scripts:
                    git clone https://github.com/solankiaakash775-create/ci-cd-with-github-action.git
                    cd ~/ci-cd-with-github-action
                    git pull origin main 
                    docker compose pull 
                    docker compose up -d 

              


    